const ESet = {
  COLLECTION_SET_COMMUNITY_3: 'A Coleção do Caçador',
  COLLECTION_SET_WEAPONS_I: 'A Coleção do Negócio Bélico',
  COLLECTION_SET_ESPORTS: 'A Coleção de eSports de 2013',
  COLLECTION_SET_BRAVO_I: 'A Coleção Bravo',
  COLLECTION_SET_WEAPONS_II: 'A 2ª Coleção do Negócio Bélico',
  COLLECTION_SET_ESPORTS_II: 'A Coleção de eSports de Fim de Ano de 2013',
  COLLECTION_SET_COMMUNITY_1: 'A Coleção da Ofensiva de Fim de Ano',
  COLLECTION_SET_WEAPONS_III: 'A 3ª Coleção do Negócio Bélico',
  COLLECTION_SET_COMMUNITY_2: 'A Coleção Fênix',
  COLLECTION_SET_COMMUNITY_4: 'A Coleção Libertação',
  COLLECTION_SET_ESPORTS_III: 'A Coleção de eSports de Férias de 2014',
  COLLECTION_SET_COMMUNITY_5: 'A Coleção Vanguarda',
  COLLECTION_SET_COMMUNITY_6: 'A Coleção Cromática',
  COLLECTION_SET_COMMUNITY_7: 'A 2ª Coleção Cromática',
  COLLECTION_SET_DUST: 'A Coleção Dust',
  COLLECTION_SET_AZTEC: 'A Coleção Aztec',
  COLLECTION_SET_VERTIGO: 'A Coleção Vertigo',
  COLLECTION_SET_INFERNO: 'A Coleção Inferno',
  COLLECTION_SET_MILITIA: 'A Coleção Militia',
  COLLECTION_SET_NUKE: 'A Coleção Nuke',
  COLLECTION_SET_OFFICE: 'A Coleção Office',
  COLLECTION_SET_ASSAULT: 'A Coleção Assault',
  COLLECTION_SET_BRAVO_II: 'A Coleção Alfa',
  COLLECTION_SET_DUST_2: 'A Coleção Dust 2',
  COLLECTION_SET_TRAIN: 'A Coleção Train',
  COLLECTION_SET_MIRAGE: 'A Coleção Mirage',
  COLLECTION_SET_ITALY: 'A Coleção Italy',
  COLLECTION_SET_LAKE: 'A Coleção Lake',
  COLLECTION_SET_SAFEHOUSE: 'A Coleção Safehouse',
  COLLECTION_SET_BANK: 'A Coleção Bank',
  COLLECTION_SET_OVERPASS: 'A Coleção Overpass',
  COLLECTION_SET_COBBLESTONE: 'A Coleção Cobblestone',
  COLLECTION_SET_BAGGAGE: 'A Coleção Baggage',
  COLLECTION_SET_CACHE: 'A Coleção Cache',
  COLLECTION_SET_GODS_AND_MONSTERS: 'A Coleção Deuses e Monstros',
  COLLECTION_SET_CHOPSHOP: 'A Coleção do Ferro Velho',
  COLLECTION_SET_KIMONO: 'A Coleção do Sol Nascente',
  COLLECTION_SET_COMMUNITY_8: 'A Coleção Falchion',
  COLLECTION_SET_COMMUNITY_9: 'A Coleção Sombria',
  COLLECTION_SET_COMMUNITY_10: 'A Coleção do Revólver',
  COLLECTION_SET_COMMUNITY_11: 'A Coleção Fogo Selvagem',
  COLLECTION_SET_NUKE_2: 'A Coleção Nuke de 2018',
  COLLECTION_SET_INFERNO_2: 'A Coleção Inferno de 2018',
  COLLECTION_SET_XRAYMACHINE: 'A Coleção Raio-X',
  COLLECTION_SET_COMMUNITY_12: 'A 3ª Coleção Cromática',
  COLLECTION_SET_COMMUNITY_13: 'A Coleção Gama',
  COLLECTION_SET_GAMMA_2: 'A 2ª Coleção Gama',
  COLLECTION_SET_COMMUNITY_15: 'A Coleção das Luvas',
  COLLECTION_SET_COMMUNITY_16: 'A Coleção Espectral',
  COLLECTION_SET_COMMUNITY_17: 'A Coleção da Operação Hidra',
  COLLECTION_SET_COMMUNITY_18: 'A 2ª Coleção Espectral',
  COLLECTION_SET_BLACKSITE: 'A Coleção Blacksite',
  COLLECTION_SET_COMMUNITY_19: 'A Coleção do Aperto',
  COLLECTION_SET_COMMUNITY_20: 'A Coleção do Horizonte',
  COLLECTION_SET_STMARC: 'A Coleção St. Marc',
  COLLECTION_SET_CANALS: 'A Coleção Canals',
  COLLECTION_SET_NORSE: 'A Coleção Nórdica',
  COLLECTION_SET_OP9_CHARACTERS: 'Agentes da Teia Fragmentada',
  COLLECTION_SET_OP10_CHARACTERS: 'Agentes da Presa Quebrada',
  COLLECTION_SET_OP11_CHARACTERS: 'Agentes da Operação Correnteza',
  COLLECTION_SET_COMMUNITY_21: 'A Coleção da Zona de Perigo',
  COLLECTION_SET_COMMUNITY_22: 'A Coleção Prismática',
  COLLECTION_SET_COMMUNITY_23: 'A Coleção Teia Fragmentada',
  COLLECTION_SET_COMMUNITY_24: 'A Coleção CS20',
  COLLECTION_SET_DUST_2_2021: 'A Coleção Dust 2 de 2021',
  COLLECTION_SET_MIRAGE_2021: 'A Coleção Mirage de 2021',
  COLLECTION_SET_COMMUNITY_25: 'A 2ª Coleção Prismática',
  COLLECTION_SET_COMMUNITY_26: 'A Coleção Fraturada',
  COLLECTION_SET_COMMUNITY_27: 'A Coleção da Operação Presa Quebrada',
  COLLECTION_SET_OP10_CT: 'A Coleção do Controle',
  COLLECTION_SET_OP10_T: 'A Coleção do Caos',
  COLLECTION_SET_OP10_ANCIENT: 'A Coleção Ancient',
  COLLECTION_SET_COMMUNITY_28: 'A Coleção do Ataque Ofídico',
  COLLECTION_SET_TRAIN_2021: 'A Coleção Train de 2021',
  COLLECTION_SET_VERTIGO_2021: 'A Coleção Vertigo de 2021',
  COLLECTION_SET_ANUBIS: 'A Coleção Anubis',
  COLLECTION_SET_COMMUNITY_29: 'A Coleção da Operação Correnteza',
  COLLECTION_SET_COMMUNITY_30: 'A Coleção dos Sonhos e Pesadelos',
  COLLECTION_SET_COMMUNITY_31: 'A Coleção do Coice',
  COLLECTION_SET_COMMUNITY_32: 'A Coleção da Revolução',
  COLLECTION_SET_COMMUNITY_33: 'A Coleção Quilowatt',
  COLLECTION_SET_COMMUNITY_34: 'A Coleção da Galeria',
  COLLECTION_SET_COMMUNITY_35: 'A Coleção Febril',
  COLLECTION_SET_ARABESQUE: 'A Coleção Arabesca',
  COLLECTION_SET_COMMUNITY_36: 'A Coleção Gênese',
  COLLECTION_SET_COMMUNITY_37: 'A Coleção Mão Morta',
  COLLECTION_SET_GRAPHIC_DESIGN: 'A Coleção do Design Gráfico',
  COLLECTION_SET_OVERPASS_2024: 'A Coleção Overpass de 2024',
  COLLECTION_SET_REALISM_CAMO: 'A Coleção Esportiva',
  COLLECTION_SET_SPY_TECH: 'A Coleção Spytech',
  COLLECTION_SET_TIMED_DROPS_ACHROMA: 'A Coleção Acromática',
  COLLECTION_SET_TIMED_DROPS_COOL: 'A Coleção Ascendente',
  COLLECTION_SET_TIMED_DROPS_EXUBERANT: 'A Coleção Arlequim',
  COLLECTION_SET_TIMED_DROPS_NEUTRAL: 'A Coleção Boreal',
  COLLECTION_SET_TIMED_DROPS_WARM: 'A Coleção Radiante',
  COLLECTION_SET_TRAIN_2025: 'A Coleção Train de 2025',
  COLLECTION_SET_XPSHOP_WPN_01: 'Item de edição limitada',
  COLLECTION_SET_AUTO_RACING: 'Coleção de Adesivos da Corrida de Automóveis',
  COLLECTION_SET_COMMUNITY_2025: 'Coleção de Adesivos da Comunidade de 2025',
  COLLECTION_SET_FRUITS_VEGGIES: 'Coleção de Adesivos das Frutas e Verduras',
  COLLECTION_SET_KC_DRBOOM: 'Coleção dos Chaveiros do Dr. Buum',
  COLLECTION_SET_KC_MISSINGLINK: 'Coleção dos Salsichaveiros',
  COLLECTION_SET_KC_ML_COMMUNITY_01: 'Coleção dos Salsichaveiros da Comunidade',
  COLLECTION_SET_KC_WEAPON_01: 'Coleção dos Chaveiros de Arminhas',
  COLLECTION_SET_STKR_CRAFT_01: 'Pacote de Adesivos Elementais',
  COLLECTION_SET_STKR_CRAFT_02: 'Pacote de Adesivos de Criação de Personagens',
  COLLECTION_SET_SUGARFACE2: '2ª Coleção de Adesivos das Calaveras',
  COLLECTION_4617: 'Coleção de Grafites do CS:GO nº 3',
  COLLECTION_4618: 'Coleção de Grafites da Zoeira',
  COLLECTION_4621: 'Coleção de Grafites do CS:GO nº 2',
} as const;

type TSet = (typeof ESet)[keyof typeof ESet];
